server:
  port: 8080
  error:
    include-message: always

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:memDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
